### PR TITLE
new implementatation of parameter combination

### PR DESCRIPTION
**Pull request by jonathanheitzmann**
I now think that the parameter combination should work. Please check for errors

### CODE REVIEW

**Review by ThorbenCarl — CHANGES_REQUESTED** [review]
For me, the result looks okay at first glance. However, I find it difficult to understand the code. `k`,`l`,`m`,`n`,... is not very helpful, more comments and meaningful variables would help.

### Changes I made:
- updated branch from `master` branch
- in: `test_vp_on_helpers.py`
  - Add `skiptif` decorator for better debugging
- in: `ValuePoolFuzzer.py`
  - Run auto formatter
  - Set `_logger` & `_value_pool` as private member
  - Add (return-)types to variables and functions (still some left)
  - Updated docstring of `fuzz()` function

### Review:
@jonathanheitzmann 
- Still to do:
  - [x] Comments should be consistently in English.
  - [x] Update UML.
  - [x] Add to all variables and functions (return-)types. Makes it much easier to read and understand.
  - [x] Please use more meaningful variables. With `k`,`l`,`m`,`n`,... it is extremely difficult to understand the code.
- Is there a mathematical approach? So that, for example, if you have `n` value_pools with `x` values each, you expect a list with `y` entries at the end? Would be an easy way to check if the results make sense.

**Comment by jonathanheitzmann** [comment]
I'm not shure with "Add to all variables and functions (return-)types. Makes it much easier to read and understand." Didn't you change already the function headers? Or what do you mean?
Yes theres a mathematical approach. The number of lists should be the product over the longest value_pool lists. The amount of the longest lists in the calculation is determined by param_combi.

**Review by dsiev — COMMENTED** [review]
In general I trust that you have tested the code and that it runs fine

**Comment by ThorbenCarl** [comment]
> I'm not shure with "Add to all variables and functions (return-)types. Makes it much easier to read and understand." Didn't you change already the function headers? Or what do you mean? Yes theres a mathematical approach. The number of lists should be the product over the longest value_pool lists. The amount of the longest lists in the calculation is determined by param_combi.

I added missing types.

**Review by ThorbenCarl — APPROVED** [review]

**Comment by ThorbenCarl** [comment]
@jonathanheitzmann @dsiev What is the current status? Have you found any new bugs?

**Comment by jonathanheitzmann** [comment]
yes and I just fixed the bug. Should I merge?

**Comment by ThorbenCarl** [comment]
> yes and I just fixed the bug. Should I merge?

If it works, there you go!

**Comment by ThorbenCarl** [comment]
@jonathanheitzmann Is there anything left to do? If not please delete branch.

**Pull request merged**
